language: node_js
node_js: v14
cache:
  - node_modules
addons:
  chrome: stable
before_install:
  - yarn global add @lhci/cli@0.4.x
script:
  - yarn
  - yarn build
  - lhci autorun --config=./lighthouserc.js
