language: node_js
node_js: v12
cache:
  - node_modules
addons:
  chrome: stable
before_script:
 - curl -o- -L https://yarnpkg.com/install.sh | bash -s
 - export PATH=$HOME/.yarn/bin:$PATH
 - yarn install
before_install:
  - yarn global add @lhci/cli@0.4.x
script:
  - yarn install
  - yarn run build
  - lhci autorun
